### ISSUE TITLE
openAI proxy

### ISSUE THREAD

**Issue by CYBki** [xianjianlf2/MindGeniusAI#16]
Hi, I added Azure OpenAI endpoint to the openAI proxy section, but it still didn't work. How can I find the url that I will write in the proxy section there?

**Comment by xianjianlf2** [comment]
Maybe you can check this file.
https://github.com/xianjianlf2/MindGeniusAI/blob/a1ae36f37e6569518e47b4e5664336c241095f79/server/utils/useOpenAIProxy.ts#L11

**Comment by xianjianlf2** [comment]
Now Azure and OpenAI also provide official libraries for more convenient use, and there are third-party libraries available as well, such as LangChain.
- [@azure/openai](https://www.npmjs.com/package/@azure/openai)
- [openai](https://www.npmjs.com/package/openai)
- [langchain js](https://js.langchain.com/docs/get_started/introduction)

**Comment by CYBki** [comment]
Thanks
________________________________
Gönderen: Mark Xian ***@***.***>
Gönderildi: 6 Mart 2024 Çarşamba 11:06
Kime: xianjianlf2/MindGeniusAI ***@***.***>
Bilgi: SEYİT ALİ YORĞUN ***@***.***>; Author ***@***.***>
Konu: Re: [xianjianlf2/MindGeniusAI] openAI proxy (Issue #16)


Now Azure and OpenAI also provide official libraries for more convenient use, and there are third-party libraries available as well, such as LangChain.

  *   @***@***.***/openai>
  *   openai<https://www.npmjs.com/package/openai>
  *   langchain js<https://js.langchain.com/docs/get_started/introduction>
