### ISSUE TITLE
openAI Proxy

### ISSUE THREAD

**Issue by machonz** [xianjianlf2/MindGeniusAI#17]
@xianjianlf2  ran the project on my machine, but it wants an open API proxy login, a url etc. where can I find it. it would be nice if you upload a description or a description as a gif in that part of the project.
Thank you

**Comment by xianjianlf2** [comment]
Hi, perhaps you could take a look at this file.
![image](https://github.com/xianjianlf2/MindGeniusAI/assets/53885024/61ef2150-2f0b-446a-805b-134b1faba320)

set your api key in this file and rename file to `.env`
