### ISSUE TITLE
openAI Proxy  error

### ISSUE THREAD

**Issue by machonz** [xianjianlf2/MindGeniusAI#18]
Hi Mark, I edited the .example.env file as you said but I get this error and I cannot run the project.
![mm_gena](https://github.com/xianjianlf2/MindGeniusAI/assets/163287919/e864f46f-91ac-4168-a843-47c432b81490)

**Comment by xianjianlf2** [comment]
Please check if the OpenAI agent's configuration is correct. 
After I re-clone and ran the code, it worked.
![image](https://github.com/xianjianlf2/MindGeniusAI/assets/53885024/d7ac9f77-5412-4cee-976a-f93dd9a82f2e)

![screent](https://github.com/xianjianlf2/MindGeniusAI/assets/53885024/0e50fa5a-8fea-41fa-a745-c6f6301197de)
