### ISSUE TITLE
after fix "dev": "npx nodemon --exec node --loader ts-node/esm index.ts"

### ISSUE THREAD

**Issue by Seaver-Zhu** [xianjianlf2/MindGeniusAI#19]
![屏幕截图 2024-07-24 163040](https://github.com/user-attachments/assets/c8a04632-abf8-443d-82a0-51554210162e)

anyway I click the website, it shows nothing
![image](https://github.com/user-attachments/assets/2d15e92e-12c8-4aad-8e40-62c9dda7071d)

**Comment by xianjianlf2** [comment]
Two terminal services need to be started, one in `server` directory and one in the project root directory, running `npm run dev`

**Comment by Seaver-Zhu** [comment]
> Two terminal services need to be started, one in `server` directory and one in the project root directory, running `npm run dev`

thank you 
![image](https://github.com/user-attachments/assets/07de3a3a-e65e-41b6-ae6c-670bf24c61ca)
Should I download vue locally?

**Comment by xianjianlf2** [comment]
yep, need to run `npm install` in both directories first
