### ISSUE TITLE
无法运行，提示错误

### ISSUE THREAD

**Issue by yqty** [xianjianlf2/MindGeniusAI#6]
![image](https://github.com/xianjianlf2/MindGeniusAI/assets/108921221/429e778b-5211-4b7c-a842-b1ed9b2844df)
![image](https://github.com/xianjianlf2/MindGeniusAI/assets/108921221/ce2bb85a-ca15-4332-b901-43c74616f218)

**Comment by xianjianlf2** [comment]
检查网络环境  能否连接上 open ai 或 Proxy 能否连接成功
---
<img width="479" alt="SCR-20230723-cpcy" src="https://github.com/xianjianlf2/MindGeniusAI/assets/53885024/06506891-5c8a-40e9-b3b8-128a7a5cf58c">
